# .travis.yml file
cache: apt
sudo: true
language: python
python: 
    - "2.7"

install:
    - conda env create --file environment.yml
    - source activate test-environment 
    - python setup.py install

script:
    - py.test --cov=archiversearch

after_success:
    - coveralls